#!/usr/bin/fish

ln -sf $PWD/search ~/.local/bin/\?

ln -sf $PWD/multiclipboard.py ~/.local/bin/mc

ln -sf $PWD/launcher.py ~/.local/bin/r

ln -sf $PWD/scripts_fish.pl ~/.local/bin/fishy

ln -sf $PWD/sunrise ~/.local/bin/sunrise

ln -sf $PWD/emo ~/.local/bin/emo

ln -sf $PWD/saferm.sh ~/.local/bin/del

ln -sf $PWD/datecp ~/.local/bin/cpd

ln -sf $PWD/gorun ~/.local/bin/gorun
